//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoonbeeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivisionFormTieHistory
    {
        public int DivisionId { get; set; }
        public bool ForSecondOrThird { get; set; }
        public int PlayerOneId { get; set; }
        public int PlayerTwoId { get; set; }
        public bool Winner { get; set; }
    
        public virtual Participant Participant { get; set; }
        public virtual Participant Participant1 { get; set; }
        public virtual Division Division { get; set; }
        public virtual Division Division1 { get; set; }
    }
}
