//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoonbeeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivisionStatus
    {
        public DivisionStatus()
        {
            this.Divisions = new HashSet<Division>();
        }
    
        public int DivisionStatusId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Division> Divisions { get; set; }
    }
}
