//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoonbeeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivisionDefault
    {
        public int DivisionDefaultId { get; set; }
        public string FriendlyId { get; set; }
        public int RankGroupId { get; set; }
        public string Genders { get; set; }
        public int AgeGroupId { get; set; }
        public int DivisionTypeId { get; set; }
        public System.DateTime DateEntered { get; set; }
        public int Order { get; set; }
    
        public virtual AgeGroup AgeGroup { get; set; }
        public virtual RankGroup RankGroup { get; set; }
        public virtual DivisionType DivisionType { get; set; }
    }
}
