//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoonbeeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivisionFormScore
    {
        public int DivisionId { get; set; }
        public int ParticipantId { get; set; }
        public float JudgeOneScore { get; set; }
        public float JudgeTwoScore { get; set; }
        public float JudgeThreeScore { get; set; }
        public float Sum { get; set; }
        public System.DateTime DateEntered { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
