//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoonbeeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public Participant()
        {
            this.DivisionFormScores = new HashSet<DivisionFormScore>();
            this.DivisionFormTieHistories = new HashSet<DivisionFormTieHistory>();
            this.DivisionFormTieHistories1 = new HashSet<DivisionFormTieHistory>();
            this.DivisionParticipants = new HashSet<DivisionParticipant>();
            this.DivisionWinners = new HashSet<DivisionWinner>();
            this.TournamentParticipants = new HashSet<TournamentParticipant>();
            this.TournamentTeams = new HashSet<TournamentTeam>();
        }
    
        public int ParticipantId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public int RankId { get; set; }
        public int HeightFeet { get; set; }
        public int HeightInches { get; set; }
        public int Age { get; set; }
        public string Style { get; set; }
        public string Form { get; set; }
        public string Weapon { get; set; }
        public int SchoolId { get; set; }
        public System.DateTime DateEntered { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool League { get; set; }
    
        public virtual ICollection<DivisionFormScore> DivisionFormScores { get; set; }
        public virtual ICollection<DivisionFormTieHistory> DivisionFormTieHistories { get; set; }
        public virtual ICollection<DivisionFormTieHistory> DivisionFormTieHistories1 { get; set; }
        public virtual ICollection<DivisionParticipant> DivisionParticipants { get; set; }
        public virtual ICollection<DivisionWinner> DivisionWinners { get; set; }
        public virtual School School { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual ICollection<TournamentParticipant> TournamentParticipants { get; set; }
        public virtual ICollection<TournamentTeam> TournamentTeams { get; set; }
    }
}
