//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoonbeeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rank
    {
        public Rank()
        {
            this.Participants = new HashSet<Participant>();
            this.RankGroups = new HashSet<RankGroup>();
        }
    
        public int RankId { get; set; }
        public string RankName { get; set; }
    
        public virtual ICollection<Participant> Participants { get; set; }
        public virtual ICollection<RankGroup> RankGroups { get; set; }
    }
}
