//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoonbeeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.Participants = new HashSet<Participant>();
            this.TournamentTeams = new HashSet<TournamentTeam>();
        }
    
        public int SchoolId { get; set; }
        public string Name { get; set; }
        public string LocationText { get; set; }
    
        public virtual ICollection<Participant> Participants { get; set; }
        public virtual ICollection<TournamentTeam> TournamentTeams { get; set; }
    }
}
