//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoonbeeLive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        public Tournament()
        {
            this.Divisions = new HashSet<Division>();
            this.TournamentParticipants = new HashSet<TournamentParticipant>();
            this.TournamentParticipants1 = new HashSet<TournamentParticipant>();
            this.TournamentTeams = new HashSet<TournamentTeam>();
        }
    
        public int TournamentId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateEntered { get; set; }
        public System.DateTime DateHeld { get; set; }
        public int SeasonId { get; set; }
    
        public virtual ICollection<Division> Divisions { get; set; }
        public virtual ICollection<TournamentParticipant> TournamentParticipants { get; set; }
        public virtual ICollection<TournamentParticipant> TournamentParticipants1 { get; set; }
        public virtual ICollection<TournamentTeam> TournamentTeams { get; set; }
        public virtual Season Season { get; set; }
    }
}
